### ISSUE TITLE
SvelteKit: when using devOptions: enabled,   warnings :   One of the glob patterns doesn't match any files. Please remove or fix the following

### ISSUE THREAD

**Issue by xmlking** [vite-pwa/vite-plugin-pwa#436]
SvelteKit: when using `devOptions: enabled = true`, I noticed the following warnings 
don't understand what caused those warnings or it is a bug 
```
precache  1 entries (0.00 KiB)
files generated
  dev-dist/sw.js
  dev-dist/workbox-d2a14864.js
warnings
  Some items were passed to additionalManifestEntries without revisioning info. This is generally NOT safe. Learn more at https://bit.ly/wb-precache.
  - /

  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/schintha/Developer/Work/SPA/svelte-starter-kit/dev-dist",
  "globPattern": "client/**/*.{js,css,ico,png,svg,webp}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/schintha/Developer/Work/SPA/svelte-starter-kit/dev-dist",
  "globPattern": "prerendered/**/*.html",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}
```

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/627951/209608385-c8bcbc5c-f678-46d0-b94b-5687cbb5aa19.png">

**Comment by BunnyTheLifeguard** [comment]
Do you have a glob pattern inside your vite config file?

**Comment by userquin** [comment]
@xmlking @BunnyTheLifeguard you can ignore this warning, on dev mode there is nothing in the sw precache, only the navigation fallback: I'll try to remove the warning changing the `globPattern` when using dev mode.

Whether or not you have a `globPattern` included doesn't matter, workbox uses a default one that includes `css`, `js` and `html`.

**Comment by danawoodman** [comment]
fwiw I'm still seeing this in a recent build with SvelteKit + dev mode enabled without a glob pattern in my config

**Comment by userquin** [comment]
@danawoodman I guess there is no way to remove the warning, if you check the dev-dist folder create, it will conly ontain the sw and the workbox-** asset: the only way to remove it is to not log workbox warnings when building it, I'll try to fix it...

**Comment by userquin** [comment]
Should be fixed in `v0.16.3`, I'll add a new entry in the docs... 

Add `suppressWarnings: true` to `devOptions`, it will generate an empty `suppress-warnings.js` inside `dev-dist` folder and change `globalPatterns` to `['*.js'].

The `additionalManifestEntries` without revision also fixed adding object notation with random string in revision.

**Comment by danawoodman** [comment]
Thanks @userquin! Will this be released in `@vite-pwa/sveltekit`?

**Comment by userquin** [comment]
Reinstall kit plugin or reinstall pwa plugin

**Comment by danawoodman** [comment]
I've removed `package-lock.json`, `node_modules`, my build directories, uninstalled and reinstalled `vite-plugin-pwa` and `@vite-pwa/sveltekit` and added `supressWarnings: true` to `devOptions` but I'm still seeing the warning. Anything else to try?

I see `@vite-pwa/sveltekit` was last updated 21 days ago on npm, is that an issue?

**Comment by userquin** [comment]
I need to update pwa kit plugin dependencies...

**Comment by userquin** [comment]
@danawoodman released `0.2.3`
