### ISSUE TITLE
updateServiceWorker() not always working 

### ISSUE THREAD

**Issue by mattoni** [vite-pwa/vite-plugin-pwa#583]
I'm using `import { useRegisterSW } from "virtual:pwa-register/react";` to manage updates. I

I've noticed occasionally (especially with multiple tabs) after the `needsRefresh` gets set to true and the popup appears, if the user clicks the button calling `updateServiceWorker()` sometimes nothing happens. The service worker is 'waiting to become active' and the `needsRefresh` fired, but it doesn't actually install it.

Usually a refresh will fix it and the  `updateServiceWorker()` will work then, but it seems to happen at random, though I've noticed it more when multiple tabs of the website are open.

Here is the logic: 

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/5110855/c9f104e7-c359-4d66-9335-22867164fca1)

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/5110855/28adc234-7d53-4cb4-86c2-415c08685b7a)

This hook is also present in the root of my app to force an update if they refresh the page, but I don't  think that is affecting the above code.

Here is the configuration for the PWA:
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/5110855/bca4348a-a6b8-4ae6-aa87-210e85b43652)

I don't see any errors appearing when this happens either, it just..doesn't work.

Any help is appreciated! Thanks.

**Comment by userquin** [comment]
should be fixed in `v0.18.0`

**Comment by JosefSaltz** [comment]
I cannot get updateServiceWorker to either reload the page successfully or activate the waiting service worker for my reload prompt React component as of 0.19.8.

**Comment by onekiloparsec** [comment]
@JosefSaltz would you mind sharing how you integrated the `skipWaiting` listener in your code? Myself, I have the follow ing Vuejs code, but I guess I could adapt. I just don't understand what `self` is, in the PWA documentation about `skipWaiting`. Thanks in advance! 

My `script setup`:

```

<script lang="ts" setup>
  import { useRegisterSW } from 'virtual:pwa-register/vue'
  import { computed } from 'vue'
  import Button from 'primevue/button'

  const intervalMS = 5 * 60 * 1000

  const { offlineReady, needRefresh, updateServiceWorker, } = useRegisterSW({
    immediate: true,
    onRegisteredSW (swUrl, r) {
      r && setInterval(async () => {
        if (!(!r.installing && navigator)) {
          return
        }

        if (('connection' in navigator) && !navigator.onLine) {
          return
        }

        const resp = await fetch(swUrl, {
          cache: 'no-store',
          headers: {
            'cache': 'no-store',
            'cache-control': 'no-cache',
          },
        })

        if (resp?.status === 200) {
          await r.update()
        }
      }, intervalMS)
    }
  })

  const closeButtonLabel = computed(() => offlineReady.value ? 'Close' : 'Ignore')

  const close = async () => {
    offlineReady.value = false
    needRefresh.value = false
  }
</script>
```

**Comment by ZandercraftGames** [comment]
I'm currently having this issue without a custom sw.js. Occasionally `needsRefresh` will be made true and when calling `updateServiceWorker()`, it does not do anything as far as I can tell and the page does not refresh (leaving anything relying on `needsRefresh` stuck).

This is my configuration:
```
VitePWA({
      registerType: 'prompt',
      injectRegister: 'script-defer',
      minify: true,
      workbox: {
        maximumFileSizeToCacheInBytes: 10 * 1024 * 1024, // 10 MB
        globPatterns: ['**/*.{js,css,html,ico,png,svg,jpg,jpeg,whl,ttf}']
      },
      manifestFilename: 'static/manifest.webmanifest',
. . .
```

**Comment by nguyenbatranvan** [comment]
> I tested this a few times using 2 tabs and instances, even reopening the browser and the tabs/instances, can you try enabling these 2 options `cleanupOutdatedCaches: true` and `clientClaims: true` in the workbox option ?
> 
>     workbox: {
>       /* other options */
>       cleanupOutdatedCaches: true, // <== this is not required, but should be used
>       clientsClaim: true,
>     },

I have the configuration of what you said, but sometimes the problem still occurs:

```
     workbox: {
            globPatterns: ["**/*.{js,css,html,svg,png,ico}"],
            cleanupOutdatedCaches: true,
            clientsClaim: true,

        },
```

**Comment by nguyenbatranvan** [comment]
> Can you check if the sw installed and activated at devtools (green) when updateServiceWorker doing nothing?
> 
> If you have periodic sync for updates, you will need to remove the setInterval once sw updatefound received. If calling update from sw registration when updatefound, the sw will be activated by the browser, that's why updateServiceWorker does nothing.

Do you have a detailed example for this? I can't visualize where to clear the interval! I've checked and the service worker is already active. Currently I'm using the default sw.js file from the plugin and not using the file I rewrote

**Comment by userquin** [comment]
Can you try with something like this (from `@vite-pwa/create` react-ts example)?
```tsx
import './PWABadge.css'

import { useRegisterSW } from 'virtual:pwa-register/react'

function PWABadge() {
  // check for updates every hour
  const period = 60 * 60 * 1000
  let interval: ReturnType<typeof setInterval> | undefined

  const {
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(swUrl, r) {
      r?.addEventListener('updatefound', () => {
        clearInterval(interval) 
      });
      if (r?.active?.state === 'activated') {
        interval = registerPeriodicSync(period, swUrl, r)
      }
      else if (r?.installing) {
        r.installing.addEventListener('statechange', (e) => {
          const sw = e.target as ServiceWorker
          if (sw.state === 'activated') {
            interval = registerPeriodicSync(period, swUrl, r)
          }
        })
      }
    },
  })

  function close() {
    
    setNeedRefresh(false)
  }

  return (
    <div className="PWABadge" role="alert" aria-labelledby="toast-message">
      { (needRefresh)
      && (
        <div className="PWABadge-toast">
          <div className="PWABadge-message">
            <span id="toast-message">New content available, click on reload button to update.</span>
              
              
          </div>
          <div className="PWABadge-buttons">
            <button className="PWABadge-toast-button" onClick={() => updateServiceWorker(true)}>Reload</button>
            <button className="PWABadge-toast-button" onClick={() => close()}>Close</button>
          </div>
        </div>
      )}
    </div>
  )
}

export default PWABadge

/**
 * This function will register a periodic sync check every hour, you can modify the interval as needed.
 */
function registerPeriodicSync(period: number, swUrl: string, r: ServiceWorkerRegistration) {
  return setInterval(async () => {
    if ('onLine' in navigator && !navigator.onLine)
      return

    const resp = await fetch(swUrl, {
      cache: 'no-store',
      headers: {
        'cache': 'no-store',
        'cache-control': 'no-cache',
      },
    })

    if (resp?.status === 200)
      await r.update()
  }, period)
}
```

**Comment by nguyenbatranvan** [comment]
> r?.addEventListener('updatefound', () => {
>         clearInterval(interval) 
>       });
>       if (r?.active?.state === 'activated') {
>         interval = registerPeriodicSync(period, swUrl, r)
>       }

I see there's a difference in the lines below, perhaps you added them yourself? Will this resolve the issue being discussed?

```
  r?.addEventListener('updatefound', () => {
        clearInterval(interval) 
      });
      if (r?.active?.state === 'activated') {
        interval = registerPeriodicSync(period, swUrl, r)
      }
```

**Comment by nguyenbatranvan** [comment]
> > I see there's a difference in the lines below, perhaps you added them yourself?
> 
> yes, I added the interval and the required logic
> 
> > Will this resolve the issue being discussed?
> 
> It should; are you testing with builds at least with 1 minute between them? workbox-window using an heuristic algh. that may break the "update" logic

ok!! tks so much! I will try
